### ISSUE TITLE
Issue with opening the application

### ISSUE THREAD

**Issue by Morgan-taco** [TheGreatRambler/Mii_to_UMii#2]
Whenever I try to open miitoumii.exe, the application just shows the cmd prompt and then closes. The same thing happens whenever I try to open a .bin file via the application.

**Comment by Morgan-taco** [comment]
I forgot to mention. I'm using my mii data from smash ultimate. That's why it's in that format.

**Comment by TheGreatRambler** [comment]
Very late but you have to run it with the command prompt, that's why I specified it in the readme. Open `cmd.exe` and navigate to the folder with the executable. Run `miitoumii.exe` and you'll see the help menu

**Comment by Morgan-taco** [comment]
Yeah...figured that out after I talked to you about it on discord a while back. lol
