### ISSUE TITLE
Dont know how to use

### ISSUE THREAD

**Issue by theman12222** [TheGreatRambler/Mii_to_UMii#4]
I ran cmd in the folder then typed -i to input a model but it just says it's an unknown command. Am I doing something wrong? Am I supposed to type something else? This is what I did in the cmd terminal, lemme know what i'm supposed to do cuz i dont think  this is it
<img width="655" alt="Screenshot_30" src="https://github.com/TheGreatRambler/Mii_to_UMii/assets/112595465/92e8ee92-d138-4d07-abaa-2179cf170517">

**Comment by TheGreatRambler** [comment]
You're supposed to use `miitoumii.exe -i [other commands]`

**Comment by theman12222** [comment]
> You're supposed to use `miitoumii.exe -i [other commands]`

Thank you

**Comment by theman12222** [comment]
So after I do miitoumii.exe -i --input, how do i specify the file?

**Comment by theman12222** [comment]
Nevermind figured it out
